
-- CUSTOMERS
CREATE TABLE CUSTOMERS(
CUSTOMERNUMBER			INT(11),
CUSTOMERNAME			VARCHAR(50) 	NOT NULL,
CONTACTLASTNAME			VARCHAR(50) 	NOT NULL,
CONTACTFIRSTNAME		VARCHAR(50) 	NOT NULL,
PHONE					VARCHAR(50) 	NOT NULL,
ADDRESSLINE1			VARCHAR(50) 	NOT NULL,
ADDRESSLINE2			VARCHAR(50),
CITY					VARCHAR(50) 	NOT NULL,
STATE					VARCHAR(50),
POSTALCODE				VARCHAR(15),
COUNTRY					VARCHAR(50) 	NOT NULL,
SALESREPEMPLOYEENUMBER	INT(11),
CREDITLIMIT				DOUBLE
)
;

ALTER TABLE CUSTOMERS 
ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (CUSTOMERNUMBER)
;

-- PAYMENTS
CREATE TABLE PAYMENTS(
CUSTOMERNUMBER			INT(11) 		NOT NULL,
CHECKNUMBER				VARCHAR(50),
PAYMENTDATE				DATE 			NOT NULL,
AMOUNT					DOUBLE 			NOT NULL
)
;

ALTER TABLE PAYMENTS 
ADD CONSTRAINT PAYMENTS_PK PRIMARY KEY (CHECKNUMBER)
;

-- ORDERS...
CREATE TABLE ORDERS(
ORDERNUMBER				INT(11),
ORDERDATE				DATE			NOT NULL,
REQUIREDDATE			DATE			NOT NULL,
SHIPPEDDATE				DATE,
STATUS					VARCHAR(15)		NOT NULL,
COMMENTS				TEXT,
CUSTOMERNUMBER			INT(11)			NOT NULL
)
;

ALTER TABLE ORDERS 
ADD CONSTRAINT ORDERS_PK PRIMARY KEY (ORDERNUMBER)
;

-- ORDER DETAILS...
CREATE TABLE ORDERDETAILS(
ORDERNUMBER				INT(11)			NOT NULL,
PRODUCTCODE				VARCHAR(15)		NOT	NULL,
QUANTITYORDERED			INT(11)			NOT NULL,
PRICEEACH				DOUBLE			NOT NULL,
ORDERLINENUMBER			SMALLINT		NOT NULL
)
;

-- PRODUCTS 
CREATE TABLE PRODUCTS(
PRODUCTCODE				VARCHAR(15),
PRODUCTNAME				VARCHAR(70)		NOT NULL,
PRODUCTLINE				VARCHAR(50)		NOT	NULL,
PRODUCTSCALE			VARCHAR(10)		NOT NULL,
PRODUCTVENDOR			VARCHAR(50)		NOT NULL,
PRODUCTDESCRIPTION		TEXT			NOT NULL,
QUANTITYINSTOCK			SMALLINT(6)		NOT	NULL,
BUYPRICE				DOUBLE			NOT NULL,
MSRP					DOUBLE			NOT NULL
)
;

ALTER TABLE PRODUCTS 
ADD CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCTCODE)
;

-- PRODUCT LINES 
CREATE TABLE PRODUCTLINES(
PRODUCTLINE				VARCHAR(50),
TEXTDESCRIPTION			VARCHAR(4000),
HTMLDESCRIPTION			MEDIUMTEXT,
IMAGE					MEDIUMBLOB
)
;

ALTER TABLE PRODUCTLINES 
ADD CONSTRAINT PRODUCTLINES_PK PRIMARY KEY (PRODUCTLINE)
;

-- EMPLOYEES
CREATE TABLE EMPLOYEES(
EMPLOYEENUMBER			INT(11),
LASTNAME				VARCHAR(50)		NOT NULL,
FIRSTNAME				VARCHAR(50)		NOT NULL,
EXTENSION				VARCHAR(10)		NOT NULL,
EMAIL					VARCHAR(100) 	NOT NULL,
OFFICECODE				VARCHAR(10)		NOT NULL,
REPORTSTO				INT(11),
JOBTITLE				VARCHAR(50)		NOT NULL
)
;

ALTER TABLE EMPLOYEES 
ADD CONSTRAINT EMPLOYEES_PK PRIMARY KEY (EMPLOYEENUMBER)
;

-- OFFICES
CREATE TABLE OFFICES(
OFFICECODE				VARCHAR(10),
CITY					VARCHAR(50)		NOT NULL,
PHONE					VARCHAR(50)		NOT NULL,
ADDRESSLINE1			VARCHAR(50)		NOT NULL,
ADDRESSLINE2			VARCHAR(50),
STATE					VARCHAR(50),
COUNTRY					VARCHAR(50)		NOT NULL,
POSTALCODE				VARCHAR(15)		NOT NULL,
TERRITORY				VARCHAR(10)		NOT NULL
)
;

ALTER TABLE OFFICES
ADD CONSTRAINT OFFICES_PK PRIMARY KEY (OFFICECODE)
;

-- FOREIGN KEYS...
ALTER TABLE PAYMENTS
ADD CONSTRAINT PAYMENTS_CUSTOMERS_FK
FOREIGN KEY (CUSTOMERNUMBER)
REFERENCES CUSTOMERS(CUSTOMERNUMBER)
;

ALTER TABLE ORDERS
ADD CONSTRAINT PAYMENTS_CUSTOMERS_FK
FOREIGN KEY (CUSTOMERNUMBER)
REFERENCES CUSTOMERS(CUSTOMERNUMBER)
;

ALTER TABLE ORDERDETAILS
ADD CONSTRAINT ORDERDETAILS_ORDERS_FK
FOREIGN KEY (ORDERNUMBER)
REFERENCES ORDERS(ORDERNUMBER)
;

ALTER TABLE ORDERDETAILS
ADD CONSTRAINT ORDERDETAILS_PRODUCTS_FK
FOREIGN KEY (PRODUCTCODE)
REFERENCES PRODUCTS(PRODUCTCODE)
;

ALTER TABLE PRODUCTS
ADD CONSTRAINT PRODUCTS_PRODUCTLINES_FK
FOREIGN KEY (PRODUCTLINE)
REFERENCES PRODUCTLINES(PRODUCTLINE)
;

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_OFFICES_FK
FOREIGN KEY (OFFICECODE)
REFERENCES OFFICES(OFFICECODE)
;

-- REFERENCIA CIRCULAR.
ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_REPORTSTO_FK
FOREIGN KEY (REPORTSTO)
REFERENCES EMPLOYEES(EMPLOYEENUMBER)
;

ALTER TABLE CUSTOMERS
ADD CONSTRAINT CUSTOMERS_EMPLOYEES_FK
FOREIGN KEY (SALESREPEMPLOYEENUMBER)
REFERENCES EMPLOYEES(EMPLOYEENUMBER)
;

