
-- Queries...

--- 1
SELECT C.CUSTOMERNAME AS CLIENTE, CONCAT(C.CONTACTFIRSTNAME,', ',C.CONTACTLASTNAME) AS CONTATO, C.COUNTRY AS PAIS, 
O.ORDERNUMBER AS PEDIDO,
SUM(OD.QUANTITYORDERED) AS QTDE_ITENS, TRUNCATE(AVG(OD.QUANTITYORDERED*OD.PRICEEACH),2) AS MEDIA_PEDIDO
FROM CUSTOMERS C 
INNER JOIN ORDERS O
ON (C.CUSTOMERNUMBER=O.CUSTOMERNUMBER)
INNER JOIN ORDERDETAILS OD 
ON (O.ORDERNUMBER=OD.ORDERNUMBER)
HAVING AVG(OD.QUANTITYORDERED*OD.PRICEEACH) > 100
GROUP BY C.CUSTOMERNAME, CONCAT(C.CONTACTFIRSTNAME,', ',C.CONTACTLASTNAME), O.ORDERNUMBER
ORDER BY C.CUSTOMERNAME, O.ORDERNUMBER
;

-- 2
-- NÃO SERÁ AGRUPADO POIS O BRO. DO PEDIDO É DESTACADO...
SELECT C.CUSTOMERNAME AS CLIENTE, 
O.ORDERNUMBER AS PEDIDO, O.STATUS, DATE_FORMAT(O.ORDERDATE,'%Y/%m') AS ANO_MES
FROM CUSTOMERS C 
INNER JOIN ORDERS O
ON (C.CUSTOMERNUMBER=O.CUSTOMERNUMBER)
GROUP BY C.CUSTOMERNAME, O.ORDERNUMBER, O.STATUS, DATE_FORMAT(O.ORDERDATE,'%Y/%m')
ORDER BY C.CUSTOMERNAME, O.ORDERNUMBER
;

-- 3
SELECT CONCAT(E.FIRSTNAME,', ',E.LASTNAME) AS FUNCIONARIO, E.JOBTITLE AS FUNCAO, E.EMAIL, 
CONCAT(EMPREPTO.FIRSTNAME,', ',EMPREPTO.LASTNAME) AS REPORTE, EMPREPTO.JOBTITLE AS FUNCAO
FROM EMPLOYEES E
LEFT OUTER JOIN EMPLOYEES EMPREPTO
ON (EMPREPTO.REPORTSTO=E.EMPLOYEENUMBER)
ORDER BY 1
;

-- 4
SELECT C.CUSTOMERNAME AS CLIENTE, CONCAT(C.CONTACTFIRSTNAME,', ',C.CONTACTLASTNAME) AS CONTATO, 
CONCAT(E.FIRSTNAME,', ',E.LASTNAME) AS VENDEDOR, 
O.ORDERNUMBER AS PEDIDO, O.STATUS, FORMAT_DATE(O.SHIPPEDDATE,'%d/%m/%Y') AS DATA_ENVIO,
OD.QUANTITYORDERED AS QUANTIDADE, O.PRICEEACH AS PREÇO,
P.PRODUCTNAME AS PRODUTO
FROM CUSTOMERS C 
INNER JOIN ORDERS O 
ON (C.CUSTOMERNUMBER=O.CUSTOMERNUMBER)
INNER JOIN ORDERDETAILS OD 
ON (O.ORDERNUMBER=OD.ORDERNUMBER)
INNER JOIN PRODUCTS P 
ON (OD.PRODUCTCODE=P.PRODUCTCODE)
LEFT OUTER JOIN EMPLOYEES E 
ON C.SALESREPEMPLOYEENUMBER=E.EMPLOYEENUMBER
ORDER BY C.CUSTOMERNAME, O.ORDERNUMBER, P.PRODUCTNAME
;


